### ISSUE TITLE
Issue focusing in text field when editing a config 

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#100]
When a user tries to edit a configuration, the cursor always moves to the end after each letter is typed. The cursor should stay where the user is typing. 

Trying to type here: 
![image.png](https://images.zenhubusercontent.com/5acf5bb24b5806bc2bcecd74/9f3dbbff-c99f-423e-884a-1d83ea6205d3)

Typed “1”, and the cursor immediately goes to end:
![image.png](https://images.zenhubusercontent.com/5acf5bb24b5806bc2bcecd74/9bc5d543-9421-4eeb-b3e2-772f9708b578)

Release notes: Cursor stays in the same location when editing a configuration

**Comment by davidangb** [comment]
I believe content & discovery is working on this: GAWB-3668

**Comment by irosenbe** [comment]
Closing out since Content and Discovery is fixing this bug in the next release.
