### ISSUE TITLE
sort job status alphabetically and by actual status

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#105]
Currently, the Status column in the Monitor tab sorts only alphabetically. As a user, I would like to see status of both whether the submission is completed as well as if there are any failed workflows. 

Is it possible to sort both alphabetically first and secondarily by status of the job (failed/ succeeded/ submitted) such that the jobs are grouped together by status? 

![image.png](https://images.zenhubusercontent.com/5acf5bb24b5806bc2bcecd74/11df7aa6-8fef-49ce-88f6-3147c7f2199d)

**Comment by davidangb** [comment]
This should be possible. Developer, take a look at the difference between `:sort-by` and `:render`, here: https://github.com/broadinstitute/firecloud-ui/blob/develop/src/cljs/main/broadfcui/page/workspace/monitor/tab.cljs#L39.

The render function considers both the submission status and underlying workflow statuses. The sort-by only considers the submission status. We'd need to create a new function for sort-by that considers both submission and workflow statuses.
