### ISSUE TITLE
Bug introduced after June 22 in method config

### ISSUE THREAD

**Issue by tmm211** [DataBiosphere/firecloud-app#106]
Issue reported by 2 users in the [forum](https://gatkforums.broadinstitute.org/gatk/discussion/comment/50261#Comment_50261).
Add or delete characters in a method config in a workspace, and you will get pushed to the end of the string after adding or deleting a single character.

Example: Suppose I have a method configuration and have an output annotation "out_MAF" that I write to the data model with the annotation "this.outMAF", and I want to add a prefix to this annotation so that the annotation is now "this.testOutMAF". For each letter I type in the word "test", I get sent to the end, meaning that I were to type without any adjustments, the annotation would be "this.tOutMAFest".

I told users that I would report an ETA. Please let me know when you think this can be prioritized.

**Comment by irosenbe** [comment]
Closing for duplication. Fix is pending release to Prod (target 7/10)
