### ISSUE TITLE
tests: use cloud-billing instead of cloud-platform oauth scope

### ISSUE THREAD

**Issue by davidangb** [DataBiosphere/firecloud-app#109]
This is follow-on work from #33. In #33, we stopped asking for oauth storage scope in the UI and updated our automated tests so that test code also doesn't ask for storage scope.

During that work, I noticed that we ask for `cloud-platform` scope - which is very broad - instead of `cloud-billing` for our billing tests. This is a much wider scope than we need, and is not representative of actual end user behavior; the UI requests `cloud-billing` for billing-related features.

Please update the test framework such that it only requests `cloud-billing` instead of `cloud-platform`. This is less trivial than it may seem on the surface ... we generate user tokens via service account impersonation: https://github.com/broadinstitute/workbench-libs/blob/develop/serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/auth/UserAuthToken.scala#L13. However, the service account in question is only able to grant `cloud-platform` and cannot grant `cloud-billing`. To fix, you'll have to:
- [x] identify the service account(s) used to generate tokens in all testing environments (see code reference above)
  - tests will run as either  firecloud-dev@broad-dsde-dev.iam.gserviceaccount.com in dev.test.firecloud.org or firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com in quality.firecloud.org
- [x] update the service account(s) so that it can grant `cloud-billing`; see the "Bootstrapping FireCloud" shared document, which has been supplanted by https://github.com/broadinstitute/fiabftw/blob/master/1.0/README.md
  - [x] firecloud-dev@broad-dsde-dev.iam.gserviceaccount.com
  - [x] firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com
- [x] update `AuthTokenScopes` in workbench-libs such that it requests `cloud-billing` instead of `cloud-platform` for billing scopes
- [ ] verify no regressions
- [ ] update https://github.com/broadinstitute/fiabftw/blob/master/1.0/README.md or any other doc to show that the service account needs cloud-billing scope

**Comment by jmthibault79** [comment]
I would like to see these actions after workbench-libs merging as well:
* update all integration tests to this workbench-libs version
* wait some time (a week or two?) for alpha and extant branches to catch up and then remove `cloud-platform` from the dev/qa/alpha test SAs

**Comment by aweng98** [comment]
all integration tests include leo, right? :)

**Comment by jmthibault79** [comment]
yes

**Comment by rebrown1395** [comment]
@davidangb pass this back to QA per priority discussion.
