### ISSUE TITLE
GAWB-3199: UI support for nested workflows in workspaces

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#11]
Description: 
Cromwell supports sub workflows and workbench can run them, great.

GAWB-3293 QA APPROVED  updates the Rawls/API call to Cromwell to return subworkflow information in the metadata.

Update the UI to display the sub workflows, including the workflow timing diagram.

Link to GAWB Ticket: https://broadinstitute.atlassian.net/browse/GAWB-3199 

Linked issues:
GAWB-3293 Expand subworkflow info in Cromwell metadata.  QA APPROVED
 (https://broadinstitute.atlassian.net/browse/GAWB-3293) 
GAWB-3378 Always requesting subworkflow metadata from Cromwell produces too much load
 (https://broadinstitute.atlassian.net/browse/GAWB-3378)

**Comment by jmthibault79** [comment]
We are deferring the Timing Diagram at this time.

**Comment by jmthibault79** [comment]
[UI design](https://docs.google.com/document/d/1irSpO7oG8y4Z9osjHRTQVnmoA6ryLIhNsbhLDd8QE8Y/edit)

[Bucket link implementation plan](https://docs.google.com/spreadsheets/d/184D_bFBjJ40ULWSbJ9kzgkn3Tkq3QQzDe2sOHUcCCT4/edit)

**Comment by jmthibault79** [comment]
Good news!  The Timing Diagram will work as-is for Subworkflows.

**Comment by jmthibault79** [comment]
https://github.com/broadinstitute/firecloud-ui/pull/1295
https://github.com/broadinstitute/firecloud-ui/pull/1297
