### ISSUE TITLE
Usability: linking to method repo

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/firecloud-app#111]
I often realise I want to make a minor change to my method's WDL (like bumping the disk or memory size), but doing so requires navigating to the MR and finding it. Both the method configuration list and the individual method configuration pages tell me which method they reference, but don't let me navigate directly to them. Making them links would make me scream less.

![image](https://user-images.githubusercontent.com/775136/42715023-21132a86-86c3-11e8-88a9-bab5ee66a06e.png)

![image](https://user-images.githubusercontent.com/775136/42715008-0f9fcf8e-86c3-11e8-9bc7-fc49cb097a3e.png)

Similarly, the flow around submissions (monitor tab, submission details, and workflow details) all have unclickable references to the method configuration I ran.

**Comment by davidangb** [comment]
Also (per Lee): link to the method configuration, when inside a submission detail page.
