### ISSUE TITLE
Implement NPS survey monkey into FireCloud 

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#114]
**Background:** To continuously track FireCloud user satisfaction, Product Group has been sending out surveys to users with a single question to track Net Promotor Score (NPS).  We've received very limited response - One hypothesis being the method of outreach as the limiting factor. 

**Requirements:** 

- Integrate Survey Monkey into FireCloud such that when all users navigate to the landing page of FireCloud, the users should receive a pop up question for NPS. This is already an option in Survey Monkey per the following screenshots, where only an HTML insert needs to be applied. 

Step1: ![image.png](https://images.zenhubusercontent.com/5acf5bb24b5806bc2bcecd74/7df39f02-9689-45be-956e-2a54788c4ed7) 

Step 2: ![image.png](https://images.zenhubusercontent.com/5acf5bb24b5806bc2bcecd74/73798127-4f33-40c5-bb51-10a092de7796)

Step 3: ![image.png](https://images.zenhubusercontent.com/5acf5bb24b5806bc2bcecd74/051537f0-1bd1-4217-8bbf-52712b01f1e0) 

**Questions:** 
- Define size of pop-up 
- Is there a way to display to new users after x amount of time? (30 days) 

**Technical Implementation: 
Release Notes:**

**Comment by irosenbe** [comment]
<script>(function(t,e,s,o){var n,c,l;t.SMCX=t.SMCX||[],e.getElementById(o)||(n=e.getElementsByTagName(s),c=n[n.length-1],l=e.createElement(s),l.type=“text/javascript”,l.async=!0,l.id=o,l.src=[“https:“===location.protocol?“https://“:”http://“,”widget.surveymonkey.com/collect/website/js/tRaiETqnLgj758hTBazgd1gUZQMi4TYLZYpb9_2B9QdV4YfkN2pQLuKkuCvtF1So9t.js”].join(“”),c.parentNode.insertBefore(l,c))})(window,document,“script”,“smcx-sdk”);</script>

**Comment by davidangb** [comment]
@irosenbe after thinking about this, the things I believe we need are:

- [ ] JavaScript snippet to include, as text (see previous comment). Question: does this snippet change when the survey is tweaked?
- [ ] access to SurveyMonkey's developer documentation on the topic of integration
- [ ] notification that the survey is designed and blessed and ready to deploy
- [ ] if we can't get a developer login to SurveyMonkey console, collaboration with someone who does have access to ensure it's working correctly once integrated into fc-ui

**Comment by jbuabbud** [comment]
According to Tiffany, SurveyMonkey uses a cookie to prevent the survey from appearing if someone has already answered or declined a survey. If someone responds to or declines the survey and clears their cookies or visits the site from a browser that blocks cookies, they'll see the survey again.

**Comment by jbuabbud** [comment]
![Screen Shot 2018-08-08 at 1.39.20 PM.png](https://images.zenhubusercontent.com/5a53ceb5a016c5b034bc91ab/117f3065-fbdc-48c9-94ef-1f8ed2b73ae7)

![Screen Shot 2018-08-08 at 1.39.42 PM.png](https://images.zenhubusercontent.com/5a53ceb5a016c5b034bc91ab/4c3ffe34-84f9-47e5-bb21-764ba40f00f3)

![Screen Shot 2018-08-08 at 1.39.30 PM.png](https://images.zenhubusercontent.com/5a53ceb5a016c5b034bc91ab/aec0ba4f-af86-4c44-8314-25c788fd544d)

![Screen Shot 2018-08-08 at 1.39.48 PM.png](https://images.zenhubusercontent.com/5a53ceb5a016c5b034bc91ab/fab57897-bbe2-4c4d-ad26-c6be300b6cd6)

**Comment by irosenbe** [comment]
Decision: Moving forward with design #2 with the icon in the bottom right hand corner.
