### ISSUE TITLE
BigQuery Staging user does not have the right permissions to query for costs

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/firecloud-app#116]
Error: `The user bigquery-staging@broad-dsde-staging.iam.gserviceaccount.com does not have permission to query table broad-gcp-billing:gcp_billing_export.gcp_billing_export_v1_001AC2_2B914D_822931.`

Other environments work fine.  We only need to update Staging.

**Comment by jmthibault79** [comment]
I have emailed Lukas to add this permission, as the [Bootstrapping Doc](https://docs.google.com/document/d/1O7Qv3dfvWKp33il5uDishlRoKXEaGzmIgiS17KCYm-A/edit#heading=h.bgajj7uge5ue) describes.

**Comment by jmthibault79** [comment]
Any ideas @jbuabbud ?

**Comment by jbuabbud** [comment]
Only thing comes to mind, has the vault token for bigquery-staging been set up?

**Comment by jmthibault79** [comment]
Lukas was able to find the issue and correct it.  Cost now works on Staging.
