### ISSUE TITLE
Workflow timing diagram is useless while the workflow is running, but useful info does exist

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/firecloud-app#118]
Here's a timing diagram for a workflow which has completed:

![image](https://user-images.githubusercontent.com/775136/42900318-9d6210c6-8a96-11e8-99f2-27000ec27ba3.png)

Here's one for a workflow which is still running:

![image](https://user-images.githubusercontent.com/775136/42900360-bb327bae-8a96-11e8-893e-e8b05d6d08de.png)

It stays like this until the workflow is complete. If I click the JES Operations link I see that my workflow has indeed gone through the pulling-docker, and localization steps and is now on running-docker, but that information isn't displayed in the timing diagram.

Can it be? I think it was once; I can't see any mention of `retry-1` in the operation info, so I'm wondering if we're failing to parse the response correctly if the workflow is running as opposed to done.

**Comment by rebrown1395** [comment]
Verify this and then toss over to Cromwell.

**Comment by davidangb** [comment]
I investigated, and it does seem as if Cromwell is not returning any timing-diagram data for running calls ... therefore, the FC UI can't display details. Filed as broadinstitute/cromwell#4487.

**Comment by rebrown1395** [comment]
Ticket made in Cromwell
