### ISSUE TITLE
GAWB-3380: Update workflow list API

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#12]
Link to GAWB ticket: https://broadinstitute.atlassian.net/browse/GAWB-3380

**Comment by jbuabbud** [comment]
[Design doc](https://docs.google.com/document/d/1cnOtHF_axDldOy7raQj5Hq2fkzq3eHdzYrQ7WZfX2xg/edit?usp=sharing)

**Comment by jbuabbud** [comment]
Which workspace permissions (project owner, owner, writer, reader, etc) must a user have in order to see cost results?
