### ISSUE TITLE
documentation change for uploading data 

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#127]
Forum post: https://gatkforums.broadinstitute.org/firecloud/discussion/9466/documentation-for-uploading-data#latest

![image](https://user-images.githubusercontent.com/38226884/43093163-4e03d286-8e7d-11e8-96d9-ac3fc6be2236.png)

That user_guide link brings you to the overall firecloud forum page: (https://software.broadinstitute.org/firecloud/documentation/)

Since you’re seeing this from the Import Metadata section, it should really bring you to the Import Metadata documentation (especially because importing metadata requires specific file formats you pretty much have to look up every time). https://software.broadinstitute.org/firecloud/documentation/article?id=10738

**Comment by davidangb** [comment]
an idea that has come up multiple times before is having persistent short urls for links like this. We could hardcode a short url into the UI like "https://broad.io/firecloud-import-metadata", and then the comms/doc team could control where that url redirects to. This means that if comms ever needs to change their documentation software, or if their IDs need to be regenerated, we won't have to redeploy firecloud. But it also means that comms agrees to manage these shortlinks, and we need to choose a shortlink vendor.
