### ISSUE TITLE
GAWB #3711: UI incorrectly states google bucket read access was disabled 

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#146]
https://broadinstitute.atlassian.net/browse/GAWB-3711 

Scope: Depending on results of investigation for reasoning of this bug, may or may not fall on FC App for completion.

**Comment by davidangb** [comment]
I spoke to Matt B, asking if broadinstitute/sam#184 related to this ticket. Matt said, "yes that's one of the symptoms and that test scenario goes through the very same code-path that i have a PR out to fix"
