### ISSUE TITLE
TOS Phase 1 (FC-UI protection): UI implementation

### ISSUE THREAD

**Issue by davidangb** [DataBiosphere/firecloud-app#149]
Requirements for this _phase_:
* All users of the FireCloud UI must agree to the FireCloud TOS

Non-requirements for this _phase_:
* No API protections in Workbench Services
* No protection for non-FireCloud apps

Requirements for this _story_:
* all FireCloud-UI users who have not previously agreed to the TOS will be shown the TOS and offered a gesture by which they can agree to it
* all authenticated features of FireCloud-UI will be unavailable to users who have not agreed to the TOS

Non-requirements for this _story_:
* No API protections in Workbench Services
* No protection for non-FireCloud apps

This story depends on #148 - you'll need those APIs in order to implement the UI protection.

architecture and implementation ideas documented at https://docs.google.com/document/d/1ZMnwjj155KkSWgV_SV4Ypv35e5ke2nJQBdaM9Qbl-aw/edit?usp=sharing

with additional notes at 
https://docs.google.com/document/d/1eAGin2SXZlFz9xhBudRas_WDSgB7VmZ0u_SgD8NTmn4/edit

**Comment by rebrown1395** [comment]
This has been handed off to team Saturn, closing this out.
