### ISSUE TITLE
Cromwell 34 updates for Aug 7-9ish release

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/firecloud-app#151]
https://github.com/broadinstitute/firecloud-develop/pull/1293

**Comment by jmthibault79** [comment]
Proposed FC testing plan, based on PR:
* Put it on a FIAB "A" and run a smoke test
* Observe that /stats returns 403 on FIAB A
* Test validation changes on FIAB A by running the specific workflow 100x
** Run the same test on a dev FIAB "B" without these changes to see that the problem does exist there
* Test that stdout/stderr does update on FIAB A and does not on FIAB B
* Doug tests Martha scopes on FIAB A or after merging to dev, as appropriate
* Gary runs the alpha-perf test after merging to alpha

**Comment by davidangb** [comment]
:+1: for test plan, assuming we (Ruchi) has appropriate access to monitor CPU on FIAB A

**Comment by jmthibault79** [comment]
Cromwell version hotfix PRs:
https://github.com/broadinstitute/firecloud-develop/pull/1299
broadinstitute/agora#263
broadinstitute/rawls#972

Cromwell config changes:
https://github.com/broadinstitute/firecloud-develop/pull/1296
