### ISSUE TITLE
GAWB-3729: Firecloud UI error servicing request POST http://app:8080/api/library/search

### ISSUE THREAD

**Issue by aweng98** [DataBiosphere/firecloud-app#153]
https://broadinstitute.atlassian.net/browse/GAWB-3729

**Comment by aweng98** [comment]
happened again https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/8713/

**Comment by davidangb** [comment]
completed by Andrea in GAWB-3729/GAWB-3729; closing this.
