### ISSUE TITLE
Abort button appears as enabled/clickable even when you don't have abort permissions

### ISSUE THREAD

**Issue by davidangb** [DataBiosphere/firecloud-app#156]
Enter a workspace on which you only have Reader permissions, with running submissions. Navigate to the Monitor tab, then enter a running submission.

**Actual**: the Abort button appears enabled/clickable. Clicking it results in an error modal (screenshot below), because aborting fails in the back end since you don't have permissions.

**Expected**: the Abort button should appear as disabled/unclickable (or not appear at all), and should not trigger a backend request to abort the submission.

![Screen Shot 2018-08-10 at 2.50.52 PM.png](https://images.zenhubusercontent.com/55b637294f7a08fbb7f3ed09/40f7a8d3-4e65-40d3-931c-570f47d26835)

**Comment by irosenbe** [comment]
Decision: Abort icon should not appear to users who do not have access to abort the job.
