### ISSUE TITLE
spike: option for cold or nearline storage 

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#159]
As a user, I would like to have the option to move my data (that's currently in a FireCloud workspace) to a different Google storage option, specifically nearline or coldline storage. Using regional vs multi-regional would also be a cost savings that I could take advantage of. This could save me up to 1/2 - 3/4 of the cost I currently pay for monthly storage since some data is referenced infrequently.

Iteration #1: API option
Iteration #2: Putting storage selection option via the UI - Most likely Saturn, and not FireCloud UI 

Storage classes for reference: https://cloud.google.com/storage/docs/storage-classes 

Items to consider: 
- Is it possible to enable storage type selection for a FireCloud bucket via an API? Does this already exist through Google? 
- How would we lock down compute such that users do not accidentally compute on coldline data and accrue large compute costs? 
- If a Google API already exists to enable this, does a FireCloud user have the right permissions to do it themselves? Does a Broad admin have the permissions? 
- Warning for users when moving storage classes; Or running compute 
- Where in the lifecycle of workspace: changing storage class beginning and middle 
- What are implications of using coldline storage? Just pricing? 

Output: 
- Tech doc with options on how a user can move their data to a different storage class - What exists today at API level, what considerations need to be put in place for user to be able to move their data  
- Scope for this tech doc: 1) can users currently move their data via api to different storage class? 2) if so, how? 3) if not, what needs to be implemented so users can move their data 4) what happens when a user computes against data in coldline/ nearline - Is it purely a price difference? 
- Out of scope for this tech doc: Warnings to users to ensure locked-down compute on this data in cold or nearline storage

**Comment by davidangb** [comment]
see also: https://cloud.google.com/storage/docs/changing-default-storage-class; https://cloud.google.com/storage/docs/changing-storage-classes
