### ISSUE TITLE
Rawls: cannot retrieve Subworkflow outputs

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/firecloud-app#160]
Found this while testing #157: because Rawls doesn't have a WorkflowRecord for Subworkflows, it can't return a Subworkflow's output.  Apply changes to Rawls similar to what we did for Subworkflow Metadata to enable outputs.

Bonus: determine which other Rawls endpoints may be affected by this.

**Comment by rebrown1395** [comment]
Won't fix.
