### ISSUE TITLE
Choose a subset of Orchestration auto-tests as "smoke" tests

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/firecloud-app#161]
QA plans to reduce the number of correctness tests we run on the real Alpha environment as part of release testing.  Instead of running the full auto-tests suite, designate some tests as Smoke Tests which would reveal major problems on failure.

The full auto-tests suite will continue to run on FIABs as part of the PR and dev merge process.

Alpha submission load testing (AKA Alpha-perf or "Gary" tests) is also unaffected by this.

**Comment by rebrown1395** [comment]
Won't fix.
