### ISSUE TITLE
step 1: background for moving storage class 

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#164]
complete background investigation to set the stage to move forward with granting users permission to modify the storage class of their data.  

1. Verify the lack of storage.buckets.update permissions 

1. Investigate if it is safe to grant workspace owners the storage.buckets.update permission, which would allow them to set default storage class and lifecycle rules. Note the impact of granting this permission to all users; however, permission to all users will not be granted until much later in the feature development 

(2) 

1. Verify that all Workbench functionality - like file preview, IGV.js, and ability to run an analysis - work correctly against both nearline and coldline data 

(1)

**Comment by jmthibault79** [comment]
`storage.buckets.update` is included as part of IAM Role Storage Legacy Bucket Owner as seen here:
https://cloud.google.com/storage/docs/access-control/iam-roles

These are the only Storage Legacy Bucket Owners, as observed via Google Console:
* Billing Account Project Owner
* Rawls Service Account

While authed as Workspace Owner:

`$ gsutil defstorageclass set COLDLINE gs://fc-ef2e0948-78ad-43be-a0d3-e013c5593272`
```AccessDeniedException: 403 joel.broad.dev@gmail.com does not have storage.buckets.update access to fc-ef2e0948-78ad-43be-a0d3-e013c5593272.```

```
$ curl -H "Authorization: Bearer `googletoken`" -H "Content-Type: application/json" \
-X PUT -d '{"storageClass": "COLDLINE"}' \
https://www.googleapis.com/storage/v1/b/fc-ef2e0948-78ad-43be-a0d3-e013c5593272?fields=storageClass
```

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "joel.broad.dev@gmail.com does not have storage.buckets.update access to fc-ef2e0948-78ad-43be-a0d3-e013c5593272."
   }
  ],
  "code": 403,
  "message": "joel.broad.dev@gmail.com does not have storage.buckets.update access to fc-ef2e0948-78ad-43be-a0d3-e013c5593272."
 }
}
```

While authed as Test Domain Admin:

`$ gsutil defstorageclass set COLDLINE gs://fc-ef2e0948-78ad-43be-a0d3-e013c5593272`
`Setting default storage class to "COLDLINE" for bucket gs://fc-ef2e0948-78ad-43be-a0d3-e013c5593272`

```
$ curl -H "Authorization: Bearer `googletoken`" -H "Content-Type: application/json" \
-X PUT -d '{"storageClass": "COLDLINE"}' \
https://www.googleapis.com/storage/v1/b/fc-ef2e0948-78ad-43be-a0d3-e013c5593272?fields=storageClass
```

```
{
 "storageClass": "COLDLINE"
}
```

**Comment by jmthibault79** [comment]
More details about question 2 from the [Epic design doc](https://docs.google.com/document/d/1tuUyUrx8C1XpmMwTGaso4e-1BxqsuETOSE4t0oGEGSI/edit?ts=5b744fc3&pli=1#heading=h.2vbcdpz0ti8h) our main concerns are:
* logging: `gsutil logging set`
* encryption: `gsutil kms encryption -d` and `gsutil kms encryption -k`

**Comment by jmthibault79** [comment]
[Google Doc](https://docs.google.com/document/d/19_pHeZbbYKRI9V4XvXP_JJk4r7in_hE8ij9k6Lkfd1k/edit) for discussion of question 2
