### ISSUE TITLE
updating registration email to users 

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#169]
update the language in the registration email to users as follows to keep information consistent with current support processes: 

1. Link to TCGA Workspaces should be removed 
2. Link to FireCloud Billing Project should be: https://software.broadinstitute.org/firecloud/search?q=billing+project#gsc.tab=0&gsc.q=billing%20project&gsc.page=1 
3. Update language in Questions section to: "If you have any questions, please post to our Forum" keeping the Forum link as follows: https://gatkforums.broadinstitute.org/firecloud/ 

knowledge-sharing document from Matt Bemis: https://docs.google.com/document/d/1lPCIgiLmNessSEo7oJuHq_TnYv6k0kJR-dezntz6JwU/edit?usp=sharing

**Comment by irosenbe** [comment]
IR to talk to Matt Bemis

**Comment by jmthibault79** [comment]
Doc from Matt: https://docs.google.com/document/d/1lPCIgiLmNessSEo7oJuHq_TnYv6k0kJR-dezntz6JwU/edit?ts=5b915ec7
