### ISSUE TITLE
Create and analyze metrics for BigQuery cost requests

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#17]
Goal: Metrics review for BigQuery work related to costs. Determine additional work as needed based on what we find. 

Description: Caching big query results for APIs includes data base schema change and logic to ensure workflow is completed before cache

Link to GAWB ticket: https://broadinstitute.atlassian.net/browse/GAWB-3383

Re-scoped on 5/29:
- Record metrics of uncached calls 
- Review metrics after a few weeks to decide whether to move forward with the original scope of this ticket and caching big query results  

Details of metrics: 
- number of workflow IDs sent to big query 
- time took to query big-query 
- total time for endpoint 
- total bytes processed - TBD, may be deprecated according to documentation 
-  number of rows returned 

Research needed on what doing with rawls metrics and whether that information is sufficient.  Currently goes to hosted graphite. 

Joel to own design of where metrics go.

**Comment by davidangb** [comment]
Let's re-assess/re-refine this one. I agree with Joel that this is premature optimization. However, I'd like to make sure we are properly recording performance metrics for the BQ additions, so we can quantify impact later and decide if caching is necessary - so we need to re-scope this.

**Comment by jmthibault79** [comment]
[BigQuery Grafana/Graphite dashboard](https://www.hostedgraphite.com/e2dc6eb6/grafana/dashboard/db/bigquery-request-durations?from=1527758863891&to=1527802063891)

**Comment by jmthibault79** [comment]
Next step: re-enable cost for List Submissions on a FIAB and update the dashboard to point to that FIAB

**Comment by jmthibault79** [comment]
[Questions Doc](https://docs.google.com/document/d/1zny5SFybJvVgdS4g4DtF6XEg73XGV7rjyySlEFVnjLg/edit?usp=sharing)

**Comment by jmthibault79** [comment]
Current state of metrics: all Google requests are logged and metrics are sent to Graphite

**Comment by jmthibault79** [comment]
BigQuery requests are often unacceptably slow.  Our usage pattern of many small requests with a requirement for low latency isn't a good fit for BigQuery.  We need to use a different system.
