### ISSUE TITLE
Remove thread-blocking transactions in Rawls

### ISSUE THREAD

**Issue by davidangb** [DataBiosphere/firecloud-app#18]
Slick versions prior to 3.2.2 had a deadlock bug: https://github.com/slick/slick/issues/1274.

Rawls contains a workaround for this bug:https://github.com/broadinstitute/rawls/blob/develop/core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/DataSource.scala#L64

Now that Slick has released 3.2.3, we can theoretically upgrade our Slick version and remove the workaround. In order to accomplish this, please:

* write a unit test that fails on 3.2.1 and passes on 3.2.3. I have personally tried to do this but have hit a wall (I can't get it to fail, ever). Some hints can be found at:
** https://github.com/slick/slick/issues/1274
** https://github.com/broadinstitute/cromwell/blob/cecb1cccffa68efc2859aa7a91be6bf34d965304/services/src/test/scala/cromwell/services/ServicesStoreSpec.scala#L45
** https://github.com/kwark/slick-deadlock/blob/82525fc/src/main/scala/SlickDeadlock.scala
* Ideally, you would also measure before/after performance benchmarks (develop branch with Slick 3.2.1 and thread-blocking transactions vs. your PR branch with Slick 3.2.3 and non-blocking transactions)

**Comment by jmthibault79** [comment]
The fix for 1274 is actually in Slick 3.2.0: https://github.com/slick/slick/commit/0a8a5d7e0124f2d588bb44cc0ccd981bb92295ff

Unfortunately it would be difficult to write a Unit Test for current Rawls dev and run it on Slick 3.1.x, because it's not available for Scala 2.12, which some of our dependencies require.
