### ISSUE TITLE
Auto-retry when "socket closed"

### ISSUE THREAD

**Issue by knoblett** [DataBiosphere/firecloud-app#188]
A user reported this [here](https://gatkforums.broadinstitute.org/firecloud/discussion/12871/socket-closed-error).

They would like FireCloud to auto-retry if this error is encountered. Rerunning his workflow did successfully complete, so this would streamline the user experience more. 

Please let me know if there is a reason why this would not be possible so I can report back to the user.

**Comment by bshifaw** [comment]
Also here : [opendj-priv-dsde-prod-broadinstitute](
https://gatkforums.broadinstitute.org/firecloud/discussion/11133/opendj-priv-dsde-prod-broadinstitute-org-636-socket-closed)

**Comment by rebrown1395** [comment]
Won't fix.
