### ISSUE TITLE
Continuing Perf/Gatling/Taurus test work

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/firecloud-app#189]
Complete the work of #158 (Perf/Gatling/Taurus tests for #24):
* Jenkins DSL version of `perf-run-single-test-until-it-fails`
* Cron job for Jenkins DSL `alpha-run-all-taurus-tests`
* replacing the Perf view by renaming the Perf-DSL view and jobs

**Comment by jmthibault79** [comment]
These docs may be helpful:
* [Workbench endpoint capacity testing for developers](https://docs.google.com/document/d/1WHiG9HQpq3utj179OS5sklHiCdFmstHAJq7S_JjcI7o/edit?pli=1#)
* [Testing on the perf environment](https://docs.google.com/document/d/1nEOlI5Mv2oehkHAhuFiryy2QNmeUJab9JyGWwBihSYc/edit?pli=1#heading=h.4fgyrm3uuais)
* https://github.com/broadinstitute/dsp-jenkins

**Comment by rebrown1395** [comment]
Won't fix.
