### ISSUE TITLE
TOS: Populate UI with test inputs for FiaB

### ISSUE THREAD

**Issue by davidangb** [DataBiosphere/firecloud-app#190]
This story could use refinement/fleshing out. For now, see https://docs.google.com/document/d/1eAGin2SXZlFz9xhBudRas_WDSgB7VmZ0u_SgD8NTmn4/edit?ts=5ba15d3e#heading=h.yobx2hu6psu

* Ensure that FireCloud UI reads its Application and TermsOfService values from config (Saturn team is likely building this, as part of the overall UI work)
* Ensure that the UI config is fungible during FiaB startup
* During FiaB startup, insert unique Application and/or TermsOfService entities into Datastore for use by this test run, then inject those unique values into FireCloud UI config.
* During FiaB populate, insert TOSResponse records for all/most of our test users under the unique Application/TermsOfService entities for this test run.
* During FiaB stop/cleanup, delete the entire unique Application/TermsOfService hierarchy used for this test run, including the TOSResponse records.

As far as a way to programmatically create/clean up Datastore entities. I’d prefer to NOT add all this functionality to the TOS API, for security reasons. We should add into Vault a service account credential that has the ability to read/write Datastore entities, then add a script to FiaB that directly calls Datastore APIs using that credential to perform population and cleanup.

**Comment by jmthibault79** [comment]
Moved the SA, Vault, and Datastore scripting pieces to #196 
Connecting FIAB scripts to UI is #197 

The above needs to exist in FIAB/config before the UI uses it.  Complete this story by coordinating with UI efforts to use these test values.
