### ISSUE TITLE
Tasks in empty scatters appear to be skipped because they are not visible

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/firecloud-app#192]
Reported by a user [here](https://github.com/broadinstitute/cromwell/issues/4136):

Im using FireCloud (workspace: broad-firecloud-dsde/dsde-methods-sv-dev)

The WDL can be found in GATK's repo: cnv_germline_cohort_workflow.wdl that imports cnv_common_tasks.wdl

This is the graph that wdltools output for that WDL
graph.pdf
graph

As you can see in the monitor's "Failure" report GermlineCNVCallerCohortMode scatter task never get calls before the dependent PostprocessGermineCNVCalls.
screen shot 2018-09-21 at 3 21 43 pm

The log confirms this if one searches for "Starting":

2018-09-20 22:45:12,561 INFO  - WorkflowExecutionActor-6d980272-4aa7-4d32-ab90-84880a0723b2 [UUID(6d980272)]: 
    Starting CNVGermlineCohortWorkflow.PreprocessIntervals
2018-09-20 23:03:42,454 INFO  - WorkflowExecutionActor-6d980272-4aa7-4d32-ab90-84880a0723b2 [UUID(6d980272)]: 
    Starting CNVGermlineCohortWorkflow.CollectCounts (95 shards), CNVGermlineCohortWorkflow.ScatterIntervals
2018-09-21 02:12:52,275 INFO  - WorkflowExecutionActor-6d980272-4aa7-4d32-ab90-84880a0723b2 [UUID(6d980272)]: 
    Starting CNVGermlineCohortWorkflow.DetermineGermlineContigPloidyCohortMode
2018-09-21 02:31:18,476 INFO  - WorkflowExecutionActor-6d980272-4aa7-4d32-ab90-84880a0723b2 [UUID(6d980272)]: 
    Starting CNVGermlineCohortWorkflow.PostprocessGermlineCNVCalls (95 shards)  
The beginning of the sam log confirms that the skipped task was initially parsed in:

2018-09-20 22:45:09,504 INFO  - MaterializeWorkflowDescriptorActor [UUID(6d980272)]: Parsing workflow as WDL draft-2
2018-09-20 22:45:09,877 INFO  - MaterializeWorkflowDescriptorActor [UUID(6d980272)]: Call-to-Backend assignments: 
    CNVGermlineCohortWorkflow.GermlineCNVCallerCohortMode -> JES, 
    CNVGermlineCohortWorkflow.DetermineGermlineContigPloidyCohortMode -> JES, 
    CNVGermlineCohortWorkflow.PreprocessIntervals -> JES, 
    CNVGermlineCohortWorkflow.ScatterIntervals -> JES, 
    CNVGermlineCohortWorkflow.PostprocessGermlineCNVCalls -> JES, 
    CNVGermlineCohortWorkflow.AnnotateIntervals -> JES, 
    CNVGermlineCohortWorkflow.CollectCounts -> JES
Notice that in the log extract above I had added new-lines and 4-blank indents to make them more readable.

It seems that the input to the missing-in-action scatter, the indexed array that it scatters on, is empty and that is the root cause of the failure....
IMO it would help to see in the log/report that the scatter has actually been observed but it simply had 0 elements which quite often may indicate that something went wrong (perhaps it should have a warning icon next to it in the report (e.g. a yellow ! triangle) .

**Comment by davidangb** [comment]
I don't have access to the original workspace in question. Could someone on this thread either give me access to that, or tell me what Cromwell returns in its `calls` section for the skipped `PostprocessGermlineCNVCalls` task? tagging @ruchim @gemmalam @cjllanwarne who were all on the original issue.

**Comment by davidangb** [comment]
the possible execution statuses that cromwell could return are here: https://github.com/broadinstitute/cromwell/blob/develop/core/src/main/scala/cromwell/core/ExecutionStatus.scala#L12-L23

**Comment by davidangb** [comment]
for the call in question, I believe cromwell metadata is returning:
```
    "CNVGermlineCohortWorkflow.PostprocessGermlineCNVCalls": [
      {
        "executionStatus": "Failed",
        "backendStatus": "Failed",
```
it's unclear how the UI could interpret this differently. This likely needs to be a discussion with cromwell team(s) to understand what needs to change on the technical end and/or what to look for in the metadata to handle this use case.

**Comment by cjllanwarne** [comment]
@davidangb I've changed the title to reflect what the underlying problem here ended up being. IMO we just need to be able to warn people when scatters are empty. 

The subsequent task which didn't expect an empty array appears to have genuinely failed but I believe that it was hard to debug because it looks like an upstream task was skipped

**Comment by rebrown1395** [comment]
Cromwell issue. @rebrown1395 make new ticket in cromwell.
