### ISSUE TITLE
GAWB-3831 Alpha env - Retrieve (Cromwell) workflow's metadata does not complete within expected time

### ISSUE THREAD

**Issue by davidangb** [DataBiosphere/firecloud-app#195]
copying onto our board from https://broadinstitute.atlassian.net/browse/GAWB-3831

see document at https://docs.google.com/document/d/1mSnBQFOdsdaQuPfLZKeUPmJoddALUseDheoRE6FARi8/edit#.

Our first attempt to solve this involved #97 and broadinstitute/firecloud-develop#1261.

Recently, we introduced broadinstitute/firecloud-develop#1346 as a band aid, but we don't expect this to solve anything.

We need to go back to the original document and implement a deeper solution - which very well may require/depend on Cromwell changes.

**Comment by rebrown1395** [comment]
Won't Fix
