### ISSUE TITLE
GAWB-3384: Show Total Run Cost in Workflow Details UI

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#20]
Link to GAWB ticket: https://broadinstitute.atlassian.net/browse/GAWB-3384

**Comment by jmthibault79** [comment]
Cost display for the Monitor tab (list all Submissions) is #66.
Single Submission cost display was completed in a previous PR.
The remaining work involves the single Workflow Details page.

**Comment by jmthibault79** [comment]
Restricting this story to top-level workflows.  Subworkflow and Call cost information is not yet available.  See #73 for more about that.

**Comment by jmthibault79** [comment]
https://github.com/broadinstitute/rawls/pull/930
https://github.com/broadinstitute/firecloud-orchestration/pull/638
https://github.com/broadinstitute/firecloud-ui/pull/1308
