### ISSUE TITLE
Adjust automatic "Schedule Maintenance" banner whenever our services are down

### ISSUE THREAD

**Issue by tmm211** [DataBiosphere/firecloud-app#203]
Currently, a banner pops up anytime our services are down that reads "Scheduled Maintenance is occurring". Because it comes up automatically, it also comes up at times when we are not doing scheduled maintenance, which is false information.

We are changing the process to put up a specific banner that says Schedule maintenance is happening when it is actually happening. @MatthewBemis is assisting with this. 

Request:
- Adjust this banner so that it does not automatically display when we put up the true schedule maintenance banner (otherwise there are two banners and that looks tacky). Ensure that when a releaser puts up the scheduled maintenance banner, this banner doesn't also display.  
- If we do keep this old banner, the wording should be updated to say something generic like, "FireCloud is down. Read more about this outage in the forum: https://gatkforums.broadinstitute.org/firecloud/categories/ask-the-firecloud-team" 
- When you are done with this ticket, merge [this PR](https://github.com/broadinstitute/firecloud-develop/pull/1382)

**Comment by rebrown1395** [comment]
Won't fix.

**Comment by tmm211** [comment]
Why @rebrown1395 :( is it a big fix? Can just the wording be updated if so?
