### ISSUE TITLE
GAWB-3363: auto-tests: check that only users who have project creation abilities claim projects from GPAlloc

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#21]
Description: 
We recently updated a lot of tests to use GPAlloc. This can be run as any user, but may sometimes fall back on creating new billing projects. Not all users have this ability, so this may cause spurious test failures.

Do one of these: audit all uses of withCleanBillingProject() and claimGPAllocProject() to ensure that they're run by users who can create billing projects, or disable calling of these functions by users who can't create billing projects, so it causes such tests to fail reliably instead of occasionally.

Comments: 
Joel: PR to disable calling: https://github.com/broadinstitute/workbench-libs/pull/106
Next: run auto-tests using this version of wb-libs/service-tests to identify the failing tests, and fix them.

Link to GAWB ticket: https://broadinstitute.atlassian.net/browse/GAWB-3363

**Comment by rebrown1395** [comment]
Won't fix.
