### ISSUE TITLE
Monitoring information not displayed for workflow

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/firecloud-app#227]
I have a simple on task WDL based workflow that runs successfully, but FireCloud displays nothing in the UI where I would expect to be able to monitor it.

I can see in the Chrome console two errors:

```
GET https://api.firecloud.org/api/nih/status 404
GET https://api.firecloud.org/api/workspaces/<workspace>/submissions/<id>/workflows/<id> 500
```

I assume it is the 500 error that is at issue here. How can we chase down the root cause?

Thanks!

**Comment by rebrown1395** [comment]
Hi @mbookman! To expedite triage on this issue please make an issue in the user forum using this link: https://gatkforums.broadinstitute.org/firecloud/ Thanks for bringing it to our attention!

**Comment by mbookman** [comment]
Looks good. Thanks!
