### ISSUE TITLE
Workflow run using workspace attribute didn't seem to work

### ISSUE THREAD

**Issue by wnojopra** [DataBiosphere/firecloud-app#236]
I have a workspace attribute, where the key is sample_to_fastq_list and value is "gs://fc-secure-17a69521-9cf8-4953-b394-c9e29de0e5d5/file_list.tsv" . It is of type string.

In my method configuration, I set one of the inputs attribute to be workspace.sample_to_fastq_list. Running this workflow leads to a failure. It seems to not even run - it goes from submitted straight to failed. Furthermore, there is nothing in the logs indicating any kind of failure related to this.

On a whim I decided to change the attribute to be the actual string "gs://fc-secure-17a69521-9cf8-4953-b394-c9e29de0e5d5/file_list.tsv" , and the workflow completed successfully. This seems to indicate an issue with the workspace attribute.

**Comment by wnojopra** [comment]
Thanks @irosenbe - It doesn't seem like there's any way for me to post a new question there, or post to existing question threads, possibly because my account is [new to the forums](https://gatkforums.broadinstitute.org/firecloud/discussion/21344/new-to-the-forum-ask-your-question-here#latest) .

**Comment by irosenbe** [comment]
Great! I had someone approve your access so I'm glad it works!

**Comment by wnojopra** [comment]
The issue was resolved in the forums - I had quotes around workspace.sample_to_fastq_list that I needed to remove. Thanks for the help.
