### ISSUE TITLE
NPS in FireCloud UI 

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#239]
Can we do another round of NPS in FireCloud UI? The goal is to get another data point before moving completely to Terra, and at a time that does not come after a period of intermittent downtime. 

Ideally it would be a pop-up rather in the side corner to try and get a large response rate.

**Comment by davidangb** [comment]
note to self: broadinstitute/firecloud-ui#1369 contains the automation test changes necessary to close the NPS popup; broadinstitute/firecloud-ui#1384 removed those changes in favor of the  more subtle icon.
