### ISSUE TITLE
Optimize entityQuery to ignore all_attribute_values

### ISSUE THREAD

**Issue by davidangb** [DataBiosphere/firecloud-app#24]
The `entityQuery` object in Rawls' `EntityComponent` will select the `all_attribute_values` column unless explicitly instructed to do otherwise. We never need to return the `all_attribute_values` column from the database - we only need it for use inside a WHERE clause. (please verify this: do we need to select it for any reason when we are inserting/updating records?)

The `all_attribute_values` column is potentially quite large, and can lead to slow queries/blocking if it is selected.

Please optimize this Slick query so we never return the `all_attribute_values` column. Feel free to change `EntityRecord` to exclude this property too, if that is helpful. I'm fine if developers are required to drop to raw SQL in order to use the column - or some other solution like that.

If you accomplish this, we can probably remove `entityQuery.withoutAllAttributes` and its associated EntityRecordLightShape, EntityRecordLiteLifted, and EntityRecordBuilder.

**Comment by davidangb** [comment]
of particular note is that `entityQuery` exists in the call stack of `loadWorkspace`, which is used in many, many places (including inside of `withWorkspaceContext`). I have seen that improving `entityQuery` has positive effects on every API that relies on `withWorkspaceContext` - which is most of them.

**Comment by jmthibault79** [comment]
The [Gatling/Taurus test run against baselines](https://fc-jenkins.dsp-techops.broadinstitute.org/view/Perf/job/perf-run-all-taurus-tests/36/) showed two potential concerns and three potential improvements.  Digging deeper:

`openWorkspacePage` may have degraded in performance, but its baseline was upgraded recently.  Maybe this was hasty - *Check again vs. the older baseline*.

`monitorAnalysis` is similar but it's a small change, within normal variation.  Don't investigate.

`loginAPIs` is a small improvement, within normal variation.  There's no reason to think the entityQuery change would affect this.  Don't investigate.

`importTSVs` is a minor improvement which is conceivable affected by this change.  It only uses a small amount of entities, however.  *Update this test to do more work*

`launchAnalysis_only_complex` is a big improvement.  *Test again to find a new baseline*

**Comment by jmthibault79** [comment]
Additional tests which may show this change better:
* listEntities (unpaginated)
* entityQuery (paginated)
* exportTSV
* copyEntities
* deleteEntities

**Comment by jmthibault79** [comment]
Re-running `openWorkspacePage` [passed](https://fc-jenkins.dsp-techops.broadinstitute.org/job/perf-taurus-openWorkspacePage/30/) against the older more conservative baseline.

**Comment by jmthibault79** [comment]
Moving Perf testing discussion to #158

Rawls PR with this change: https://github.com/broadinstitute/rawls/pull/944
