### ISSUE TITLE
Banner on Firecloud to preview Terra

### ISSUE THREAD

**Issue by kjcorbin** [DataBiosphere/firecloud-app#283]
On 3/20 we should
* Remove the free credits banner for all users.
* Add a banner to FireCloud that reads:
"On May 1st FireCloud will get a new look as it becomes [powered by Terra](https://software.broadinstitute.org/firecloud/blog?id=23627). Please click [here](http://app.terra.bio) to test-drive the new experience."

The link to Terra should be context aware and allow the user to see the same page, workspace or location they are currently on in FireCloud in Terra

**Comment by davidangb** [comment]
discussion/clarification:

>> On 3/20 we should

> Does it need to be 3/20 exactly? Does time of day matter?

I am fine with this going out a day early on the 19th.
 
>>  Remove the free credits banner for all users.

> I assume we are still keeping the backend functionality of offering free credits to new registrants, correct? We're just removing the visual banner from FireCloud UI but keeping free credits in Terra UI?

Correct to both questions.
 
>> Add a banner to FireCloud that reads: "On May 1st FireCloud will get a new look as it becomes powered by Terra. Please click here to test-drive the new experience."

> As previously discussed,  this banner is dismiss-able, right? The easiest route is to make it dismissable until the user reloads the page, such as logging in again or opening in a new tab. Does it need to be more sophisticated than that?

No additional complexity is needed, that sounds great 
 
>> The link to Terra should be context aware and allow the user to see the same page, workspace or location they are currently on in FireCloud in Terra

> This is by far the biggest implementation challenge, because there are so many differences between Terra UI and FireCloud UI - pages and URLs don't cleanly map 1:1. Realistically, and given the time constraint, we can make a best effort.  

Best effort is great. I had a hunch this might not be super easy.
