### ISSUE TITLE
GAWB-3351: Linking to FC Status Page

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#3]
As a user, I want to be able to easily see if FireCloud is down to know whether my workflows will run. One possible solution is to link to http://status.firecloud.org/ somewhere in FireCloud.

The link "FireCloud Status" should be displayed in the FireCloud footer.

Screen Shot 2018-04-09 at 8.19.12 AM.png

GAWB ticket: https://broadinstitute.atlassian.net/browse/GAWB-3351

**Comment by jbuabbud** [comment]
firecloud-develop config change: https://github.com/broadinstitute/firecloud-develop/pull/1102
firecloud-ui (main code changes): https://github.com/broadinstitute/firecloud-ui/pull/1272
