### ISSUE TITLE
GAWB-3367: Remove storage scopes from FC

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#33]
Description: 
As a user of FireCloud and Saturn, I should be able to use either platform without needing to be granted advanced scopes (specifically for this ticket, Google Cloud Storage).

Verily analysts supporting BVDP and AMP-PD driver projects cannot make use of this system unless this is done.

Implementation Notes:
We do actually use the storage scope in a few places in orchestration. Start in HttpGoogleServicesDAO. getDownload(), but please audit the code to see if there are any other uses. I believe but am not 100% certain that outside of orch, everything else uses a pet service account and doesn't need the storage scope. Orch should switch to using a pet or find some other solution.

Of course, you'll have to test to look for regressions.

This scope needs to be removed from two places: 
1. The UI's oauth request at https://github.com/broadinstitute/firecloud-ui/blob/develop/src/cljs/main/broadfcui/auth.cljs#L29
2. The API's oauth request in swagger-ui, found in multiple locations in https://github.com/broadinstitute/firecloud-orchestration/blob/develop/src/main/resources/swagger/api-docs.yaml

Link to GAWB ticket: https://broadinstitute.atlassian.net/browse/GAWB-3367

-----

tech doc: https://docs.google.com/document/d/10cUiKLIAvYc-RVYkxYteTPy_drdqi267u9XYv_lUQgE/edit?usp=sharing

update 2018-04-20 David An:
I have audited services, and I believe the only service that needs updating is orchestration. Orch makes storage requests with the user's token, which therefore requires the user to grant storage scopes.

In the short term, we could reduce storage scope from devstorage.full_control to devstorage.read_only, but we want to remove the scope entirely.

See HttpGoogleServicesDAO. getDownload() and HttpGoogleServicesDAO.getObjectMetadata() to start. Side note: it would be nice to rewrite these methods using Google client libs instead of direct REST calls, but that's not a requirement for this ticket.

To use a pet service account instead of the user's credential, make a request to Sam: https://sam.dsde-dev.broadinstitute.org/#!/Google/getPetServiceAccountKey. This returns the pet's json. From there, you can use workbench-libs' GoogleCredentialModes.Json.toGoogleCredential to get a credential. From there, you can either get an access token or use the credential within Google client libraries.

The big obstacle I see is that:
* the Sam API to get a pet requires a project name
* the Orch APIs that work with storage (https://firecloud-orchestration.dsde-dev.broadinstitute.org/#/Storage) do not require a project name. 
Therefore I'm stuck at the moment trying to figure out how to retrofit the existing APIs to work with a pet. How can we do this in a backwards-compatible manner?

**Comment by bradtaylor** [comment]
@davidangb Any updates here?

Looking at the orch apis, they appear to reference a bucket/object. The bucket is under a google project. Given that the user has been given access to see stuff in this project, can we assume that they have a pet in this project?  Would that be true for UI users going through a workspace but maybe not true for API only users? Could we make them a pet in that project?

**Comment by irosenbe** [comment]
Scope for FireCloud App Team: Update Orchestration storage APIs to call this new Sam API, then execute storage operations as the pet instead of as the user

Cloud Accounts Team will implement a new API in Sam that returns a pet SA for the current user without requiring a project name.

**Comment by irosenbe** [comment]
API in sam that returns a pet SA is in review: https://broadinstitute.atlassian.net/browse/GAWB-3609
