### ISSUE TITLE
GAWB-3068: Auto completion of email addresses when sharing workspace

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#34]
Project Managers frequently share workspaces with the same collaborators. As a project manager, I would like to have an auto complete functionality so the email address of individuals who I've shared with already in FireCloud are auto-populated when the user begins typing in the desired email address. Functionality to be similar to what already exists for group population per the attached screenshot.

This will improve usability of FireCloud for PMs and reduce the amount of time it takes a PM to share data via FireCloud.

![Screen Shot 2018-01-16 at 11.22.34 AM.png](https://images.zenhubusercontent.com/5acf5bb24b5806bc2bcecd74/3ca57c3b-98db-408f-8352-8a19d9c022f1)

Link to GAWB ticket: https://broadinstitute.atlassian.net/browse/GAWB-3068

**Comment by davidangb** [comment]
to discuss with Ilyana:
* what is the set of users to show? tracking "users I've already shared with" is complex. 
** if we list user emails here, any privacy/security concerns?
* ordering of dropdown - currently unordered, what should it be?
* max size of dropdown?

**Comment by irosenbe** [comment]
1. Connecting with Bernick on sharing - What are the options? 1) Show all FireCloud users 2) Other? 
2. Ordered alphabetically 
3. Let's say show 7 email addresses with a scroll functionality - Can we mock this up and see how it looks on the page?

**Comment by jbuabbud** [comment]
See the design doc here: https://docs.google.com/document/d/1Vbf7B7LWvJ-zwzoFC3JuaUzEMOeDVAYZm79koJi6Qjg/edit

**Comment by bradtaylor** [comment]
@jbuabbud That design doc is not related to this issue. Mixed up link?

**Comment by jbuabbud** [comment]
Thanks for bringing that to my attention @bradtaylor! Replaced with the correct link.
