### ISSUE TITLE
GAWB-3553: Looping over all workspaces and locking them causes Rawls to run out of memory

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#43]
Problem:
Alex was trying to lock all of the workspaces in broad-dsde-dev using a script that serially loops over all of these workspaces and calls the endpoint to lock them. After a few iterations of this script Rawls runs out of memory and dev becomes unaccessible. This is an easy way to bring down the system. 

Alex can provide steps to reproduce this

Solutions? 

Link to GAWB ticket: https://broadinstitute.atlassian.net/browse/GAWB-3553

**Comment by rebrown1395** [comment]
Won't fix.
