### ISSUE TITLE
Database deadlock seen in tests

### ISSUE THREAD

**Issue by davidangb** [DataBiosphere/firecloud-app#46]
Alex Weng has seen a database deadlock during automated tests. Please investigate, as this could be affecting end users in production. It's possible this is also contained in the test environment, since the fiab mysql has much different performance characteristics than the production mysql.

The autotest is not a reliable reproduction case. We've only seen this error once or a few times (check with Alex to see how many).

Suggested investigation steps:
* scour Kibana to see if production has logged this error anytime recently
* scour Sentry to see if production has logged this error anytime recently
* read through the autotest code to see if you can isolate a reproduction case
* ???

screenshot:
![2018-04-18_14-16-00-359_MethodConfigSpec.png](https://images.zenhubusercontent.com/55b637294f7a08fbb7f3ed09/b6a83941-3423-4ea3-9c82-238dc1bcdf8a)

stack trace from test failure:
[https://app.zenhub.com/files/128805630/22f9cbab-7d19-48d4-82f4-854b54744aa4/download](https://app.zenhub.com/files/128805630/22f9cbab-7d19-48d4-82f4-854b54744aa4/download)

**Comment by aweng98** [comment]
a more recent case https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/5491/

**Comment by rebrown1395** [comment]
Won't fix.
