### ISSUE TITLE
Remove plus.me scope

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/firecloud-app#48]
Saturn asks for the following scope:
https://www.googleapis.com/auth/plus.me 

Per David Glazer this is completely redundant with userinfo.profile. Doug also says we don't need it. See:
https://docs.google.com/document/d/1IHVPXa1ZiZ2bd49rUa2QNh03e_vC2AzTL_pjjcBst5Y/edit?ts=5adf5f06#

This scope is not problematic. However, it should be removed on the principle that the less we ask for, the better.

**Comment by davidangb** [comment]
FireCloud does not ask for the plus.me scope. This change needs to happen in the Saturn codebase, not FireCloud.

**Comment by davidangb** [comment]
The FireCloud UI asks for email and profile scopes - plus devstorage, which we will be removing. Relevant code is here: https://github.com/broadinstitute/firecloud-ui/blob/develop/src/cljs/main/broadfcui/auth.cljs#L27. So no - we do not request openid scope.

**Comment by bradtaylor** [comment]
It appears openid scope is applied implicitly by google.
