### ISSUE TITLE
Upgrade to Cromwell 32 as soon as released!

### ISSUE THREAD

**Issue by davidbernick** [DataBiosphere/firecloud-app#51]
Please work with Red Team and upgrade Cromwell as soon as you can in FC. This is a doc about the release/verification process and Cromwell. 

https://docs.google.com/document/d/1EEzwemE8IedCplIwL506fiqXr0262Pz4G0x6Cr6V-5E/edit

**Comment by irosenbe** [comment]
Checklist for FireCloud to accept new Cromwell: https://docs.google.com/document/d/1EEzwemE8IedCplIwL506fiqXr0262Pz4G0x6Cr6V-5E/edit?ts=5ae1e543
