### ISSUE TITLE
GAWB-2985: Billing projects are no longer in alphabetical order

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#6]
Regression-y bug

In the Create Workspace or clone modal, the billing project dropdown used to show the billing projects in alphabetical order.

Now it is in a seemingly random order:
Screen Shot 2017-12-14 at 10.53.22 AM.png

Note by David An: take a look at where Rawls returns billing projects for the user - it's returning a set, not a list.

Link to GAWB ticket: https://broadinstitute.atlassian.net/browse/GAWB-2985

**Comment by jbuabbud** [comment]
PR: https://github.com/broadinstitute/rawls/pull/901
