### ISSUE TITLE
Method Config page hides errors

### ISSUE THREAD

**Issue by MattPutnam** [DataBiosphere/firecloud-app#77]
The Rawls "validate method config" endpoint avoids hitting Agora, and thus doesn't know which inputs/outputs are optional. It therefore reports "expected stuff but end of input found" errors on optional fields left blank. The UI handles this by ignoring any errors on optional inputs/outputs, but this covers up legitimate errors.

Instead, it should only ignore errors when the field is blank.

TODO: document simple reproduction steps to illustrate this issue.

**Comment by jmthibault79** [comment]
(I've been talking with Matt about this)

Not sure we can ignore errors in all cases when the field is blank because we don't know whether it's optional without checking with Agora.

**Comment by rebrown1395** [comment]
Won't fix.
