### ISSUE TITLE
GAWB-3364: New Relic Single-Page-Application browser instrumentation

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#8]
Description: 
As a FireCloud app developer, admin, or stakeholder, I want to understand how our customers actually use FireCloud and what their experience is like.

One source of information towards that end is application instrumentation. Currently, the FireCloud UI has Google Analytics embedded, but Google Analytics (GA) does not work well with single-page applications like ours - at least without significant customization. New Relic, however, claims to work well with single-page applications.

Please prototype New Relic (NR) instrumentation and see if it offers us any benefit over GA - a low bar. If we see benefit, please deploy this instrumentation to production.

Acceptance criteria:

prototype of NR instrumentation
go/no-go, based on prototype results
NR instrumentation in production, based on go/no-go
GA removed from app, if NR is a go
Implementation details:

See https://docs.newrelic.com/docs/browser/single-page-app-monitoring/get-started/introduction-single-page-app-monitoring for documentation. You may also want https://newrelic.wistia.com/medias/afx5wa23f3.
When instrumenting, make sure to separate production from dev/alpha/staging/perf/fiab/local/demo/etc
Google Analytics dashboard at https://analytics.google.com
NR dashboard at https://rpm.newrelic.com/accounts/1862859/browser

Comments:
Joel - We're specifically looking for information about which parts of the site users click on. Google Analytics -> Behavior -> Overview shows that 100% of users visit "/" which is not useful. New Relic should be able to show us which tabs users click on, for example. 

Margaret - Just to clarify if need be, GA and New Relic offer different functionality. GA is about site usage (visitors, referalls, page views, clicks, etc). New Relic is for monitoring of performance and reliability (throughput, error rate, page load time, etc). It's not either/or. Though it's true that GA is not offering us much value now. Amplitude might be a better alternative here, though we would need to be vetted for our use case.

Link to GAWB ticket: https://broadinstitute.atlassian.net/browse/GAWB-3364

**Comment by jmthibault79** [comment]
No release notes: not user-facing
