### ISSUE TITLE
Comms wants the ability to post public workspaces

### ISSUE THREAD

**Issue by tmm211** [DataBiosphere/firecloud-app#84]
Comms is in charge of posting Featured workspaces. However, to feature a workspace, they need the ability to make it public. Making it public requires admin access. No team member has admin access. 

Can we make it so that doing this does not require admin access? 

Right now to make a workspace public, there's a Rawls admin endpoint: https://rawls.dsde-prod.broadinstitute.org/#!/admin/grantAllUserReadAccess

**Comment by davidangb** [comment]
we've handled other endpoints like this (e.g. free trial endpoints) by making a managed group and checking membership in that group.

**Comment by jmthibault79** [comment]
Cloud Accounts team will take this.  https://broadinstitute.atlassian.net/browse/GAWB-3796
