### ISSUE TITLE
Bug: Workflow details not showing up

### ISSUE THREAD

**Issue by tmm211** [DataBiosphere/firecloud-app#85]
Tested with two workspaces:

1. Launch a submission.
2. Submission completes. Succeeds.
3. Go to Monitor tab. Click "View" to see the workflow details.
4. Nothing appears. See screenshot![Screen Shot 2018-06-01 at 3.34.33 PM.png](https://images.zenhubusercontent.com/5955bb2361b4ca3b0a72c63f/c5106625-0493-4551-92d4-8983ace30059)

**Comment by jmthibault79** [comment]
@tmm211  Do you only see this in Workspaces with spaces in the names?

**Comment by tmm211** [comment]
yes! Good catch.

**Comment by irosenbe** [comment]
Matt fixed. Ticket can be closed.
