### ISSUE TITLE
make banner color more prominent (regression?)

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#86]
a user reported on the forum that the alert banner is now gray which is hard to see against the white background. as a user, i would like to see alerts prominently so i know to look when critical information is being displayed. can you check to see if this can be replicated? 

outputs of this ticket: 
- list of all instances where banner shows up in FireCloud, and respective color for each instance 
- if the banner is indeed gray, change back to the red alert 

Report from forum: 
http://gatk.vanillaforums.com/discussion/12134/firecloud-status-banner-is-now-grey
"The firecloud status banner has recently changed colors from red to grey, which has very little contrast to the background colors and is very hard to notice now.  Would it be possible to switch back to the original red, or some other color with high contrast to the white background?"

**Comment by davidangb** [comment]
The banner color change was an intentional choice in https://github.com/broadinstitute/firecloud-ui/pull/1255, approved by Moran as PO ... @irosenbe connect with her to discuss history?

**Comment by irosenbe** [comment]
Intentional per: https://github.com/broadinstitute/firecloud-ui/pull/1255
