### ISSUE TITLE
GAWB-3378: Always requesting subworkflow metadata from Cromwell produces too much load

### ISSUE THREAD

**Issue by irosenbe** [DataBiosphere/firecloud-app#9]
Description: 
After  GAWB-3293 QA APPROVED  we now set expandSubWorkflows to true in Rawls -> Cromwell metadata GET calls. Because Rawls makes many of these calls, and each requires a meaningful amount of CPU/memory/DB work and data transfer on the Cromwell side, this has been causing problems.

We still want subworkflow metadata (and sub-sub-sub-workflow metadata, etc.), but we should only retrieve what we need, rather than always requesting the entire tree. This can span multiple API calls, for simplicity.

Create a design doc with a plan and coordinate with Cromwell and Field Ops.

Comment: 
Implementation plan, based on the Design Doc discussion:

Set up or access an environment with a past submission using a substantial tree of subworkflows, or run a new submission with this.

Use curl to call Cromwell GET Metadata for the top level workflow with expandSubWorkflows=true and record the payload size. Run it multiple times, attempting to overload Cromwell's memory (as observed by 503 responses and memory graphs in Google Console).

After re-deploying Cromwell, make curl calls with expandSubWorkflows=false and record the payload size. Try to overload again (should not be able to do this).

Use curl again to call with expandSubWorkflows=true and explicit selection of desired keys. Record payload size and try to overload. If both of these results are good, update Rawls to set expandSubWorkflows=true and take key parameters. Update FC-UI to pass the set of desired keys as parameters.

Link to GAWB Ticket: https://broadinstitute.atlassian.net/browse/GAWB-3378

Unblocks UI support for nested workflows: https://broadinstitute.atlassian.net/browse/GAWB-3199

**Comment by jmthibault79** [comment]
Resolved by https://github.com/broadinstitute/rawls/pull/913
