### ISSUE TITLE
Fix error message when adding non-existant user

### ISSUE THREAD

**Issue by knoblett** [DataBiosphere/firecloud-app#91]
A user reported this [here](https://gatkforums.broadinstitute.org/firecloud/discussion/12243/need-better-error-message-on-adding-users-to-groups). 

When I go to add a user to a group, and that user is not yet registered in FireCloud, I get the error message below. I know in the past, the error message shown was simply "kate.noblett@gmail.com not found," so I'm guessing something is just going wrong with the parsing in this modal. 

![image](https://user-images.githubusercontent.com/13629186/41610397-1b7a7ebe-73bb-11e8-8727-caf3f19843b9.png)

I believe the error message is the same if I were to add/share with a non-existant user anywhere in the UI, not just trying to add a user to a group. I haven't had a chance to test everything though.

**Comment by davidangb** [comment]
I'm guessing this is a regression from broadinstitute/rawls#908. When managed groups moved from rawls to Sam, I theorize that the error message seen by the UI changed. When the UI tries to pull out the nice "user not found" message, it can no longer find it.
