### ISSUE TITLE
Notifications- email links broken when there are spaces in the workspace name

### ISSUE THREAD

**Issue by tmm211** [DataBiosphere/firecloud-app#99]
Lee mentioned here: https://gatkforums.broadinstitute.org/firecloud/discussion/12287/are-the-links-in-email-notifications-unable-to-handle-spaces-in-workspace-names#latest

Bug in notification emails when we include links to workspaces with spaces in the name. For example: 
David Benjamin has given you OWNER access to the following workspace: https://portal.firecloud.org/#workspaces/broad-firecloud-dsde/Mutect2 WDL testing

This link above is broken in gmail, since the email does not have %20 for the spaces. If you click the link, you will get a page not found error.

**Comment by irosenbe** [comment]
Matt fixed in Production.
